s = {}
name = input("Enter your name:- ")
lang = input("Enter your fav lang:- ")
s.update({name:lang})
name = input("Enter your name:- ")
lang = input("Enter your fav lang:- ")
s.update({name:lang})
name = input("Enter your name:- ")
lang = input("Enter your fav lang:- ")
s.update({name:lang})
name = input("Enter your name:- ")
lang = input("Enter your fav lang:- ")
s.update({name:lang})
name = input("Enter your name:- ")
lang = input("Enter your fav lang:- ")
s.update({name:lang})
print(s)